name: PHP Extension Updater
description: Monitors a given list of PHP extensions and opens a PR if newer versions exist.
author: pantheon-systems
branding:
  icon: file-plus
  color: yellow
inputs:
  dependencies-yml:
    description: The path to the list of dependencies in a dependencies.yml file.
    required: true
    type: string
    default: ''
  output-file:
    description: The path to a separate, plaintext file to update the changes to (in addition to dependencies.yml).
    required: false
    type: string
    default: ''
  default-branch:
    description: The name of the default branch on the repository that is being altered.
    required: false
    type: string
    default: 'main'
  dry-run:
    description: Run the action without creating a PR.
    required: false
    type: boolean
    default: false
runs:
  using: composite
  steps:
    - name: Install yq
      uses: mikefarah/yq@v4
    - name: Check Dependencies
      shell: bash
      run: |
        ./bin/validate-dependencies-yml-schema.sh ${{ inputs.dependencies-yml }}
        ./bin/dependency-check-pr.sh
      env:
        DEPENDENCIES_YML: ${{ inputs.dependencies-yml }}
        OUTPUT_FILE: ${{ inputs.output-file }}
        DRY_RUN: ${{ inputs.dry-run }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        GH_TOKEN: ${{ github.token }}
        THIS_REPO: ${{ github.repository }}
        ACTIVE_BRANCH: ${{ github.ref }}
